### ISSUE TITLE
Disable users from streaming in multiple tabs. Allow 2 for development.

### ISSUE THREAD

**Issue by Justin-Leung** [HamishBrindle/shitfacetime#7]
Don't like people stream in more than 1 tab, this will prevent some local state description errors.

The error occurs when the browser is confused about connections and tabs. It might send the stream data from the wrong tab which might be closed.

Still not sure about this.

**Comment by Justin-Leung** [comment]
@HamishBrindle for this, create a button for the page that says indicates an error occurred possibly due to them having multiple browsers open.

Have the button reload the page. I'll create a call back to toggle the button/alert on and off for you.

**Comment by HamishBrindle** [comment]
To prevent multiple tabs from the same user, we may want to look at using express's session ID rather than the peer ID to match people up? Maybe a combination of both, because the problem is, when someone opens up a new tab, they're being assigned a new peerjs ID.
